AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  learnning_serverless

# SAMテンプレート共通の設定
Globals:
  Api:
    # APIGatewayの名前はswagger.yamlに書くのではなく、ここに記入する
    # swagger.yamlにはステージ変数しか渡すことができないため、swagger.yamlで環境ごとの差異を吸収することができない
    Name: learnning-serverless-apigw
  Function:
    Timeout: 29
    # 環境変数
    Environment:
      Variables:
        TZ: Asia/Tokyo
        LOG_LEVEL: 'DEBUG'

Resources:
  #  _                    _         _            _    ____ ___
  # | |    __ _ _ __ ___ | |__   __| | __ _     / \  |  _ \_ _|
  # | |   / _` | '_ ` _ \| '_ \ / _` |/ _` |   / _ \ | |_) | |
  # | |__| (_| | | | | | | |_) | (_| | (_| |  / ___ \|  __/| |
  # |_____\__,_|_| |_| |_|_.__/ \__,_|\__,_| /_/   \_\_|  |___|

  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorld-function
      Description: 
      CodeUri: app/build
      Handler: index.handler
      Runtime: python3.6
      Role: 
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
  Hello:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-name-function
      Description: 
      CodeUri: app/build
      Handler: hello.handler
      Runtime: python3.6
      Role: 
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /hello/{name}
            Method: get
  GetDBList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-db-list-function
      Description: 
      CodeUri: app/build
      Handler: get_db_list.handler
      Runtime: python3.7
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /getlist
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /getlist
            Method: post

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Lambda-Execution-Role
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonDynamoDBFullAccess'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
